name: Test Production Deployment

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker compose build -f docker-compose.prod.yml
      - name: Run tests
        run: |
          docker compose -f docker-compose.prod.yml up
          docker compose -f docker-compose.prod.yml ps
          docker compose -f docker-compose.prod.yml logs -f
      - name: Teardown
        run: docker compose down -f docker-compose.prod.yml