"""add devis_id to envelope tracking for auto-signing

Revision ID: 002_add_devis_id
Revises: 35a78dd7d68a
Create Date: 2026-01-08 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_devis_id'
down_revision = '35a78dd7d68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envelope_tracking', sa.Column('devis_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_envelope_tracking_devis_id', 'envelope_tracking', 'devis', ['devis_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_envelope_tracking_devis_id', 'envelope_tracking', type_='foreignkey')
    op.drop_column('envelope_tracking', 'devis_id')
    # ### end Alembic commands ###

