"""add interest_rate_ranges table for min-max interest rates

Revision ID: 003_add_interest_rate_ranges
Revises: 0ad1ae286a43
Create Date: 2026-02-03 10:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "003_add_interest_rate_ranges"
down_revision = "0ad1ae286a43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interest_rate_ranges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("minimum", sa.Float(), nullable=False),
        sa.Column("maximum", sa.Float(), nullable=False),
        sa.Column("interests", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interest_rate_ranges")
    # ### end Alembic commands ###
