"""add_renovation_field_to_clients

Revision ID: 0ad1ae286a43
Revises: 001_recalc_devis
Create Date: 2026-02-03 08:50:43.665782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad1ae286a43'
down_revision = '001_recalc_devis'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renovation', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'])
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.drop_column('renovation')

    # ### end Alembic commands ###
