"""Initial migration

Revision ID: 20140ec4e9f6
Revises: 
Create Date: 2025-12-22 07:54:37.937146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20140ec4e9f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('margin_rate', sa.Float(), nullable=False),
    sa.Column('margin_rate_location', sa.Float(), nullable=False),
    sa.Column('location_time', sa.Integer(), nullable=False),
    sa.Column('location_subscription_cost', sa.Float(), nullable=False),
    sa.Column('location_interests_cost', sa.Float(), nullable=False),
    sa.Column('general_conditions_sales', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('taux_tva', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('taux_tva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('parameters')
    # ### end Alembic commands ###
