"""Changed articles description to reference

Revision ID: 35a78dd7d68a
Revises: 8f46ad91408a
Create Date: 2026-01-07 09:10:34.801528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a78dd7d68a'
down_revision = '8f46ad91408a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # Add reference column as nullable first
        batch_op.add_column(sa.Column('reference', sa.Text(), nullable=True))
    
    # Copy data from description to reference (outside batch context)
    op.execute("UPDATE articles SET reference = description WHERE reference IS NULL")
    
    with op.batch_alter_table('articles', schema=None) as batch_op:
        # Make it non-nullable after populating
        batch_op.alter_column('reference', nullable=False)
        batch_op.create_unique_constraint(None, ['id'])
        # Drop the old description column
        batch_op.drop_column('description')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('remise',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('envelope_tracking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('envelope_tracking_envelope_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_envelope_tracking_envelope_id'))
        batch_op.create_index(batch_op.f('ix_envelope_tracking_envelope_id'), ['envelope_id'], unique=True)

    with op.batch_alter_table('taux_tva', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('taux_tva', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('envelope_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envelope_tracking_envelope_id'))
        batch_op.create_index(batch_op.f('ix_envelope_tracking_envelope_id'), ['envelope_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('envelope_tracking_envelope_id_key'), ['envelope_id'])

    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('remise',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
