"""Add snapshot for devis

Revision ID: 43ba27985d43
Revises: 83dbf2833f5e
Create Date: 2025-12-23 09:25:29.005925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ba27985d43'
down_revision = '83dbf2833f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signed_data', sa.JSON(), nullable=True))

    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_unitaire_ht_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('taux_tva_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_ht_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_tva_snapshot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_ttc_snapshot', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'taux_tva', ['taux_tva_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('montant_ttc_snapshot')
        batch_op.drop_column('montant_tva_snapshot')
        batch_op.drop_column('montant_ht_snapshot')
        batch_op.drop_column('taux_tva_snapshot')
        batch_op.drop_column('prix_unitaire_ht_snapshot')

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('signed_data')
        batch_op.drop_column('signed_at')

    # ### end Alembic commands ###
