"""add selected_scenario to devis

Revision ID: 59f7b4e441da
Revises: 43ba27985d43
Create Date: 2026-01-02 12:03:05.721022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f7b4e441da'
down_revision = '43ba27985d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_scenario', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('selected_scenario')

    # ### end Alembic commands ###
