"""Initial migration

Revision ID: 6a6b691510f3
Revises: 
Create Date: 2025-12-22 08:20:27.858121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6b691510f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('rue', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=False),
    sa.Column('caduque', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('margin_rate', sa.Float(), nullable=False),
    sa.Column('margin_rate_location', sa.Float(), nullable=False),
    sa.Column('location_time', sa.Integer(), nullable=False),
    sa.Column('location_subscription_cost', sa.Float(), nullable=False),
    sa.Column('location_interests_cost', sa.Float(), nullable=False),
    sa.Column('general_conditions_sales', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taux_tva',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('taux', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=345), nullable=False),
    sa.Column('mdp', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prix_achat_HT', sa.Float(), nullable=False),
    sa.Column('prix_vente_HT', sa.Float(), nullable=False),
    sa.Column('taux_tva_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taux_tva_id'], ['taux_tva.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('devis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('montant_HT', sa.Float(), nullable=False),
    sa.Column('montant_TVA', sa.Float(), nullable=False),
    sa.Column('montant_TTC', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('devis_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('devis_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['devis_id'], ['devis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devis_articles')
    op.drop_table('devis')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('taux_tva')
    op.drop_table('parameters')
    op.drop_table('clients')
    # ### end Alembic commands ###
