"""Add location and apport to devis

Revision ID: 6d166331ca2c
Revises: 6a6b691510f3
Create Date: 2025-12-22 10:03:44.842247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d166331ca2c'
down_revision = '6a6b691510f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_location', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('first_contribution_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('first_contribution_amount')
        batch_op.drop_column('is_location')

    # ### end Alembic commands ###
