"""Add envelope_id for devis sending

Revision ID: 83dbf2833f5e
Revises: e1c177942812
Create Date: 2025-12-23 07:41:15.423548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dbf2833f5e'
down_revision = 'e1c177942812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envelope_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('envelope_id')

    # ### end Alembic commands ###
