"""Add location monthly and total fields to devis

Revision ID: a28bee557863
Revises: 6d166331ca2c
Create Date: 2025-12-22 10:18:03.832035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28bee557863'
down_revision = '6d166331ca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_monthly_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_total', sa.Float(), nullable=True))
        batch_op.alter_column('first_contribution_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.alter_column('first_contribution_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
        batch_op.drop_column('location_total')
        batch_op.drop_column('location_monthly_total')

    # ### end Alembic commands ###
