"""remove_unused_docusign_fields_from_models

Revision ID: b132ac0e32d5
Revises: 002_add_devis_id
Create Date: 2026-01-08 13:49:59.286319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b132ac0e32d5'
down_revision = '002_add_devis_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('envelope_id')

    with op.batch_alter_table('envelope_tracking', schema=None) as batch_op:
        batch_op.drop_column('callback_url')
        batch_op.drop_column('notification_status')
        batch_op.drop_column('notified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envelope_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notification_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('callback_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))

    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envelope_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
