"""add commentaire to devis articles

Revision ID: bee70c0965a6
Revises: efb9ef2b0cb6
Create Date: 2025-12-22 11:37:01.533680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee70c0965a6'
down_revision = 'efb9ef2b0cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis_articles', schema=None) as batch_op:
        batch_op.drop_column('commentaire')

    # ### end Alembic commands ###
