"""add params for entreprise

Revision ID: e1c177942812
Revises: efb9ef2b0cb6
Create Date: 2025-12-22 12:35:02.952769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c177942812'
down_revision = 'bee70c0965a6'
branch_labels = None
depends_on = None


def upgrade():
    # Add with temporary defaults to satisfy existing rows
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_address_line1', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_address_line2', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_zip', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_city', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_phone', sa.String(length=50), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_email', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_iban', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_tva', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_siret', sa.String(length=64), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('company_aprm', sa.String(length=64), nullable=False, server_default=''))

    # Drop server defaults after creation
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.alter_column('company_name', server_default=None)
        batch_op.alter_column('company_address_line1', server_default=None)
        batch_op.alter_column('company_address_line2', server_default=None)
        batch_op.alter_column('company_zip', server_default=None)
        batch_op.alter_column('company_city', server_default=None)
        batch_op.alter_column('company_phone', server_default=None)
        batch_op.alter_column('company_email', server_default=None)
        batch_op.alter_column('company_iban', server_default=None)
        batch_op.alter_column('company_tva', server_default=None)
        batch_op.alter_column('company_siret', server_default=None)
        batch_op.alter_column('company_aprm', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameters', schema=None) as batch_op:
        batch_op.drop_column('company_aprm')
        batch_op.drop_column('company_siret')
        batch_op.drop_column('company_tva')
        batch_op.drop_column('company_iban')
        batch_op.drop_column('company_email')
        batch_op.drop_column('company_phone')
        batch_op.drop_column('company_city')
        batch_op.drop_column('company_zip')
        batch_op.drop_column('company_address_line2')
        batch_op.drop_column('company_address_line1')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
