"""add location HT fields

Revision ID: efb9ef2b0cb6
Revises: a28bee557863
Create Date: 2025-12-22 10:58:43.165168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb9ef2b0cb6'
down_revision = 'a28bee557863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_monthly_total_ht', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_total_ht', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devis', schema=None) as batch_op:
        batch_op.drop_column('location_total_ht')
        batch_op.drop_column('location_monthly_total_ht')

    # ### end Alembic commands ###
