"""add envelope tracking table for docusign

Revision ID: f1d2e3c4b5a6
Revises: e1c177942812
Create Date: 2026-01-07 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d2e3c4b5a6'
down_revision = 'e1c177942812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'envelope_tracking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('envelope_id', sa.String(length=255), nullable=False),
        sa.Column('callback_url', sa.String(length=2048), nullable=True),
        sa.Column('requester_host', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('signed_at', sa.DateTime(), nullable=True),
        sa.Column('notified_at', sa.DateTime(), nullable=True),
        sa.Column('notification_status', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('envelope_id')
    )
    op.create_index('ix_envelope_tracking_envelope_id', 'envelope_tracking', ['envelope_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_envelope_tracking_envelope_id', table_name='envelope_tracking')
    op.drop_table('envelope_tracking')
    # ### end Alembic commands ###
